name: github pages

on:
  push:
    branches:
    - master

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: install mkdocs
      run: |
        pip install --upgrade pip
        pip install "mkdocs ~= 1.0.4"

    - name: build site
      run: mkdocs build

    - uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
